# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UizaSDK' do
  platform :ios, '9.0'
  use_frameworks!

  pod 'Alamofire'
  pod 'NKModalViewManager'
	pod 'NKButton'
	pod 'FrameLayoutKit'
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'LFLiveKit_'
	pod 'NVActivityIndicatorView/AppExtension'
  pod 'Sentry'

end

target 'UizaSDK-tvos' do
	platform :tvos, '10.0'
	use_frameworks!
	
	pod 'Alamofire'
	pod 'SwiftyJSON'
	
end

target 'UizaBasicExample' do
	platform :ios, '9.0'
	use_frameworks!
	
	pod 'Alamofire'
	pod 'NKModalViewManager'
	pod 'NKButton'
	pod 'FrameLayoutKit'
	pod 'SDWebImage'
	pod 'SwiftyJSON'
	pod 'LFLiveKit_'
	pod 'NVActivityIndicatorView/AppExtension'
  pod 'Sentry'
	
end

target 'UizaCastingExample' do
  platform :ios, '9.0'
  use_frameworks!
  
  pod 'Alamofire'
  pod 'NKModalViewManager'
  pod 'NKButton'
  pod 'FrameLayoutKit'
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'LFLiveKit_'
  pod 'NVActivityIndicatorView/AppExtension'
  pod 'Sentry'
  pod 'google-cast-sdk', '4.3.4'
  
end

target 'UizaAdsExample' do
  platform :ios, '9.0'
  use_frameworks!
  
  pod 'Alamofire'
  pod 'NKModalViewManager'
  pod 'NKButton'
  pod 'FrameLayoutKit'
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'LFLiveKit_'
  pod 'NVActivityIndicatorView/AppExtension'
  pod 'Sentry'
  pod 'GoogleAds-IMA-iOS-SDK', '3.8.1'
  
end

target 'UizaCastingAndAdsExample' do
  platform :ios, '9.0'
  use_frameworks!
  
  pod 'Alamofire'
  pod 'NKModalViewManager'
  pod 'NKButton'
  pod 'FrameLayoutKit'
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'LFLiveKit_'
  pod 'NVActivityIndicatorView/AppExtension'
  pod 'Sentry'
  pod 'google-cast-sdk', '4.3.4'
  pod 'GoogleAds-IMA-iOS-SDK', '3.8.1'
  
end

