# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UizaSDKExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'UizaSDK', '6.8'
	pod 'SwiftIcons'
  pod 'AFDateHelper'

end
