platform :ios, '10.0'
workspace 'UizaSDKExamples'

target 'UizaSDKBasicExample' do
    project 'UizaSDKBasicExample/UizaSDKBasicExample.xcodeproj'
    use_frameworks!
    pod 'UizaSDK', git: 'https://github.com/uizaio/uiza-sdk-player-ios.git', tag: '7.6.2'
    pod 'Alamofire'
end

target 'UizaSDKCastingExample' do
    project 'UizaSDKCastingExample/UizaSDKCastingExample.xcodeproj'
    use_frameworks!
    pod 'UizaSDK', git: 'https://github.com/uizaio/uiza-sdk-player-ios.git', tag: '7.6.2'
    pod 'google-cast-sdk'
    pod 'Alamofire'
end

target 'UizaSDKGoogleAdsExample' do
    project 'UizaSDKGoogleAdsExample/UizaSDKGoogleAdsExample.xcodeproj'
    use_frameworks!
    pod 'UizaSDK', git: 'https://github.com/uizaio/uiza-sdk-player-ios.git', tag: '7.6.2'
    pod 'GoogleAds-IMA-iOS-SDK'
    pod 'Alamofire'
end
